# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-16 16:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duration', models.DurationField(verbose_name='Duration in weeks')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Value')),
                ('status', models.BooleanField(default=True, verbose_name='Active?')),
                ('created_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
