# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-16 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveSmallIntegerField(verbose_name='Duration in weeks'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
